### ISSUE TITLE
Check that references to node/capability/relationship types in a RM are valid

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/semantic-reasoner#12]
Right now, if there are references to node/capability/relationship types in requirements, capabilities, interfaces, if the type exists neither in KB nor in the local resource model, a reference is created in KB ontology which is not valid.
This is semantic reasoner's bug.
**Example**
_sodalite.capabilities.hpc.ConfiguredJob_  is defined neither in KB nor in the local resource model
```
  sodalite.nodes.hpc.job.torque: 
    description: >
      torque job 
    derived_from: tosca.nodes.SoftwareComponent
    requirements:
      - configured_job:
          node: sodalite.nodes.hpc.job.torque.configuration
          capability: sodalite.capabilities.hpc.ConfiguredJob 
          relationship: tosca.relationships.DependsOn    
```
Those references are also in capabilities and interfaces:
e.g.
```
 capabilities:
      job:
        type: sodalite.capabilities.hpc.CompleteJob
```

```
  interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
```

A fix has been prepared. With the fix, if  _sodalite.nodes.hpc.wm.torque_ definition exists neither in KB nor in the local resource model, the KB throws an error. 
A fix has been prepared in my local environment, I do not deploy it on the server http://160.40.52.200/ since I notice that some definitions of node types are missing such as:
**sodalite.capabilities.hpc.ConfiguredJob, sodalite.capabilities.modak.ModakEndpoint, sodalite.relationships.jobHostedOn**
Maybe other node type definitions are also missing in KB of the server, and I have not located them.
So before I deploy the fix on the server, and push it to the master branch, we should ensure that there are definitions for all the references.
I notice that there are cyclic references between the resource models. For example, I noticed those cyclic references in torque.rm.ttl, torque_conf_base.rm.ttl, output_hpc.rm.ttl. Since there are cyclic references between the splitted resource models, those resource models cannot be saved without getting an error that a node type does not exist.
Therefore, this issue can be resolved by not having splitted models, but adding the related node types definitions in one resource model ttl based on the fix prepared in issue #8.

**Conclusion:**
1. Ensure that all the node, capability, relationship types are defined. 
2. Resolve cyclic references by defining the types within one model instead of one model (I cannot think of other solution)
3. To be tested on the KB server
