### ISSUE TITLE
Artifact file extension converted into URI

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/semantic-reasoner#138]
For an artefact type defined in RM as
```yaml
artifact_types:
    sodalite.artifacts.TextualFile:
        derived_from: tosca.artifacts.File
        description: 'Textual artifact type'
        mime_type: 'text/plain'
        file_ext: ["txt"]
        properties:
            creator:
                description: 'Author of the file'
                type: string
                required: false
```
its AADM JSON representation contains `file_ext` attribute as a URI, not a list with actual values
```json
"https://www.sodalite.eu/ontologies/workspace/1/artifacts/sodalite.artifacts.TextualFile": {
    "type": "https://www.sodalite.eu/ontologies/tosca/tosca.artifacts.File",
    "isNodeTemplate": false,
    "class": "artifact_types",
    "properties": [
      {
        "http://purl.org/dc/elements/1.1/creator": {
          "description": "Author of the file",
          "specification": {
            "required": false,
            "type": {
              "https://www.sodalite.eu/ontologies/tosca/string": {
                "label": "string"
              }
            }
          }
        }
      }
    ],
    "mime_type": "\"text/plain\"",
    "file_ext": "https://www.sodalite.eu/ontologies/workspace/1/artifacts/ParamClassifier_fojl2iit4pkrrgphum25nbnsdh"
```
