### ISSUE TITLE
get_artifact function is missing

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/semantic-reasoner#139]
https://github.com/SODALITE-EU/ide/tree/master/dsl/org.sodalite.dsl.examples/artifacts
For operation parameter defined in RM as
```yaml
text_file_artifact:
  description: 'Text file artifact input'
  type: string
  default: get_artifact: 
    entity: SELF
    artifact: artifacts/opera.nodes.file.text_file
```
AADM JSON is
```json
  "text_file_artifact": {
    "default": {},
    "type": {
      "https://www.sodalite.eu/ontologies/tosca/string": {
        "label": "string"
      }
    }
  }
```
As well as for AADM node property defined as 
```yaml
properties:
  json_file: get_artifact:
    entity: SELF
    artifact: json_file
```
AADM JSON is
```json
  "properties": [
    {
      "https://www.sodalite.eu/ontologies/workspace/1/artifacts/json_file": {}
    }
  ]
```
