### ISSUE TITLE
Ansible DSL

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/semantic-reasoner#40]
```
node_types:
  sodalite.nodes.DockerNetwork:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      name:
        type: string
        description: The name of the network
        required: true
   ...
    interfaces:
      Standard:
        type: tosca.interfaces.node.lifecycle.Standard
        operations:
          create:
            inputs:
              docker_network_name:    { default: { get_property: [ SELF, name ] } }
            implementation:
              primary: playbooks/add_network.yml 
```

TOSCA gives the possibility to define which are the operations that can be executed on the node types, such as _create_, _delete_.
TOSCA is application agnostic, which means that does not have information related to the implementation of the application.
But through interfaces, scripts can be executed through the lifecycle of the application (create, stop, start e.t.c.) such the initialization of a database. Those scripts are linked to the operations of interfaces, as we see in the example above.
Those scripts can be python scripts, ansible playbooks e.t.c. For sodalite, we use ansible playbooks as artifacts.
TOSCA and Ansible are two seperate things. 
The 'bridge' between TOSCA and Ansible is the interfaces in the node type. 

**1. Pass info from TOSCA to ansible**
An editor is prepared in IDE for authoring Ansible DSL. 
The operation create or docker_network_name should be passed to the playbook.
There are two options
a. Through cross-model references, b) If this approach does not work and we need to rely on the KB content
**2. Autocompletion when authoring ansible dsl in ide**
As presented in [presentation here](https://docs.google.com/presentation/d/1zZ5A8_8_U033y3lQEPE-RuJb1BOqfPCkQ0gqDwQ5Sjg/edit#slide=id.ga69fdb710b_0_0)
Auto-completion should be provided both for the words belonging to the syntax and to the name of modules.
In order to provide the second feature, all the names of the modules need to be saved in the KB.
More info here: https://github.com/SODALITE-EU/semantic-reasoner/issues/38 

**3. Ansible metamodel**
Save ansible metamodel to KB so as defect predictor to predict bugs for ansible by applying semantic reasoner.
Saving of ansible will be done in a different api than saveAADM/RM so delay in time will not be an issue
