### ISSUE TITLE
Get operations from interface types for a given namespace

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/semantic-reasoner#53]
### Requirements
**API**: e.g. operations_from_interface_types(imports)
where imports - a list containing namespaces
by default the operations from the global namespace are returned.

For example in this deployment model from radon:
[here](https://github.com/xlab-si/xopera-opera/blob/master/examples/policy_triggers/service.yaml#L53)
The operations for _radon.interfaces.scaling.AutoScale_ interface type are _retrieve_info_ and _autoscale_.

 ```
radon.interfaces.scaling.AutoScale:
    derived_from: tosca.interfaces.Root
    operations:
      retrieve_info:
        description: Operation for autoscaling.
        implementation: playbooks/retrieve_info.yaml
      autoscale:
        description: Operation for autoscaling.
        implementation: playbooks/auto_scale.yaml
```

**For each returned operation, provide the interface type where it is defined.**
### Testing
For **testing**, as examples, you can save a custom resource model that has interface types:

[policies.radon.rm.txt.txt](https://github.com/SODALITE-EU/semantic-reasoner/files/5898342/policies.radon.rm.txt.txt)
its corresponding yaml is [here](https://github.com/xlab-si/xopera-opera/blob/master/examples/policy_triggers/service.yaml#L53)

and also  there are tosca normative types in Tier 0 (normative types of tosca) saved in the default graph:
[tosca normative interface types](https://github.com/SODALITE-EU/ide/blob/master/dsl/org.sodalite.dsl.examples/xopera/xopera_stdlib_1_3.rm#L443)

### **Sample response:**
The response could be:

```
{
   "data":[
      {
         "https://www.sodalite.eu/ontologies/workspace/1/radon/retrieve_info":{
            "label":"retrieve_info",
            "type":"https://www.sodalite.eu/ontologies/workspace/1/radon/radon.interfaces.scaling.AutoScale"
         }
         ...
      },
      {
         "https://www.sodalite.eu/ontologies/tosca/create":{
            "label":"create",
            "type":"https://www.sodalite.eu/ontologies/workspace/1/tosca/tosca.interfaces.node.lifecycle.Standard"
         }
        ...
        ...
      }
   ]
}
```
