### ISSUE TITLE
saveTOSCA: node_template with missing property that is not required causes an error

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/semantic-reasoner#69]
## Current behaviour

node_template without a property that defined as `required: False` in corresponding node_type causes an error in saveTOSCA method
E.g saving a security rule without a description 
```
    security-rules-node-exporter:  
      type: sodalite.nodes.OpenStack.SecurityRules 
      properties:
        ports:
         ports-tcp-9100-9100:  
            port_range_max: 9100 
            remote_ip_prefix: 0.0.0.0/0
            port_range_min: 9100 
            protocol: tcp
        group_name: node-exporter
```
returns
```
        {
            "type": "RequiredProperty",
            "info": {
                "name": "group_description",
                "context": "security-rules-node-exporter",
                "description": "Missing required property."
            }
        },
```
while node type is:
```
  sodalite.nodes.OpenStack.SecurityRules:  
    derived_from: tosca.nodes.Root 
    properties:  
      group_name:  
        description: Name of the security group in openstack. 
        required: True 
        type: string 
      ports:  
        required: False 
        constraints:  
          - min_length: 1 
        type: map 
        entry_schema:  
          type: sodalite.datatypes.OpenStack.SecurityRule 
      group_description:  
        description: Description of the security group in openstack. 
        required: False 
        type: string 
        default: ''
```
## Expected behaviour

TOSCA is saved without errors
