### ISSUE TITLE
TOSCA Mapper -  adjust names of types/templates

### ISSUE THREAD

**Issue by zoevas** [SODALITE-EU/semantic-reasoner#74]
PDS would add namespaces to nodes_types and node_templates. Reasoner would need to parse it and trim namespaces if necessary. In such a way, we will have a valid TOSCA, and Reasoner would not need to guess the namespaces.
The output would be like this:

```
tosca_definitions_version: tosca_simple_yaml_1_3 
data_types: 
  openstack_testbed/sodalite.datatypes.OpenStack.SecurityRule:  
    derived_from: tosca.datatypes.Root 
    properties:  
      protocol:  
        required: True 
        type: string 
        default: tcp 
        constraints:  
          - valid_values: ['tcp', 'udp', 'icmp'] 
      port_range_min:  
        required: True 
        type: tosca.datatypes.network.PortDef 
      port_range_max:  
        type: tosca.datatypes.network.PortDef 
        required: True 
      remote_ip_prefix:  
        default: 0.0.0.0/0 
        required: True 
        type: string 
node_types:
  openstack_testbed/sodalite.nodes.OpenStack.SecurityRules:  
    derived_from: tosca.nodes.Root 
    properties:  
      group_name:  
        description: Name of the security group in openstack. 
        required: True 
        type: string 
      ports:  
        required: False 
        constraints:  
          - min_length: 1 
        type: map 
        entry_schema:  
          type: openstack_testbed/sodalite.datatypes.OpenStack.SecurityRule 
  openstack_testbed/sodalite.nodes.OpenStack.KeyPair:
    derived_from: tosca.nodes.Root
    properties:
      name:
        type: string
        description: OpenStack Key Pair name          
topology_template:
  node_templates:
    openstack_testbed/security-rules-database-access:  
      type: openstack_testbed/sodalite.nodes.OpenStack.SecurityRules 
      properties:
        ports:
         ports-tcp-5432-5432:  
            port_range_max: 5432 
            remote_ip_prefix: 0.0.0.0/0
            port_range_min: 5432 
            protocol: tcp
        group_name: database-access
    openstack_testbed/test-key:  
      type: openstack_testbed/sodalite.nodes.OpenStack.KeyPair
      properties:
        name: test-key
      requirements:  
        - dependency: openstack_testbed/security-rules-database-access
```
